name: "Refactor"
description: "🔨 코드 리팩토링 (기능 변경 없이 코드 개선)"
labels: ["🔨 refactor"]
body:
  - type: markdown
    attributes:
      value: |
        ## 🔨 Refactor 요청 템플릿
        어떤 부분의 구조를 개선할 것인지 명확하게 작성해 주세요.

  - type: textarea
    attributes:
      label: ✨ 리팩토링 대상
      description: 리팩토링이 필요한 구체적인 컴포넌트, 함수 또는 파일 경로를 작성해 주세요.
      placeholder: 예) /components/Button.tsx - 불필요한 props 전달 제거
    validations:
      required: true

  - type: textarea
    attributes:
      label: 리팩토링 이유
      description: 리팩토링이 필요한 이유를 적어 주세요. (가독성, 성능, 재사용성 등)
      placeholder: 예) Response DTO가 너무 복잡하여 가독성이 떨어짐. 단순화 필요.

  - type: input
    attributes:
      label: 담당자
      description: "GitHub ID로 입력해 주세요. 예: @your-id"
      placeholder: "@username"
    validations:
      required: true

  - type: input
    attributes:
      label: 🔄 관련 이슈
      description: "연결할 이슈 번호를 입력하세요. 예: #456"
      placeholder: "#456"

  - type: markdown
    attributes:
      value: |
        ---
        감사합니다! 코드 품질 향상에 기여해 주셔서 고맙습니다.